databases:
  - name: sparkshed
    databaseName: sparkshed
    user: sparkshed

services:
  - type: web
    name: sparkshed
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn inventoryproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sparkshed
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
