# Generated by Django 4.1.1 on 2022-10-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparkshed', '0005_alter_kititem_kit_kitdelivery_itemdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdelivery',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sparkshed.itemorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitdelivery',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sparkshed.kitorder'),
            preserve_default=False,
        ),
    ]
