# Generated by Django 4.2.13 on 2024-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkshed', '0007_item_description_alter_item_name_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='recipient',
            field=models.CharField(default='Default Recipient', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitorder',
            name='recipient',
            field=models.CharField(default='Default Recipient', max_length=120),
            preserve_default=False,
        ),
    ]
