# Generated by Django 4.1.1 on 2022-09-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_item_alter_order_name_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='item',
        ),
    ]
