# Generated by Django 4.1.1 on 2022-09-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order_created_date_order_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
